[user]
name = "hmuto111"
email = "182398097+hmuto111@users.noreply.github.com"

[ui]
editor = "vim"
merge-editor = "vscode"

[fix.tools.biome]
command = ["pnpm", "--silent", "exec", "biome", "check", "--write", "--stdin-file-path", "$path"]
patterns = ["glob:'**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx,html,css,json,jsonc}'"]

