[tools]
node = "latest"
pnpm = "latest"

[bootstrap.packages]
apt = "zsh"

[bootstrap.user]
login_shell = "/usr/bin/zsh"


[tasks.cleanup]
description = "システム全体のキャッシュ掃除"
run = """
  echo "Cleaning Docker..." && docker system df && docker volume ls -qf dangling=true | xargs -r docker volume rm && docker images -f 'dangling=true' -q | xargs -r docker rmi && docker container prune --force --filter 'until=168h' && docker ps --filter 'status=exited' | grep 'weeks ago' | awk '{print $1}' | xargs -r docker rm && docker builder prune && docker system df
  echo "Cleaning npm cache..." && npm cache clean --force
  echo "Cleaning pnpm store..." && pnpm store prune
"""

[tasks.doctor]
description = "環境診断とシムの再生成"
run = "mise doctor && mise reshim"
